export const SET_AUDIO_DURATION = 'SET_AUDIO_DURATION';
export const SET_AUDIO_CURRENT_TIME = 'SET_AUDIO_CURRENT_TIME';
export const SET_AUDIO_PROGRESS = 'SET_AUDIO_PROGRESS';
export const SET_AUDIO_VOLUME = 'SET_AUDIO_VOLUME';
export const TOGGLE_MUTE = 'TOGGLE_MUTE';
