export const SET_AUDIO_DURATION = 'SET_AUDIO_DURATION';
export const SET_AUDIO_IS_PLAYING = 'SET_AUDIO_IS_PLAYING';
export const SET_AUDIO_VOLUME = 'SET_AUDIO_VOLUME';
export const TOGGLE_MUTE = 'TOGGLE_MUTE';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
