export const ADD_COLLECTION = 'ADD_COLLECTION';
export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const UPDATE_COLLECTION_TRACKS = 'UPDATE_COLLECTION_TRACKS';
export const DELETE_COLLECTION = 'DELETE_COLLECTION';

export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const FETCH_COLLECTIONS_DONE = 'FETCH_COLLECTIONS_DONE';
export const SET_SPECIAL_COLLECTION = 'SET_SPECIAL_COLLECTION';
