export const START_PROCESS_SOURCES = 'START_PROCESS_SOURCES';
export const END_PROCESS_SOURCES = 'END_PROCESS_SOURCES';
export const FETCH_SOURCES = 'FETCH_SOURCES';
export const FETCH_SOURCES_DONE = 'FETCH_SOURCES_DONE';
export const SAVE_SOURCES = 'SAVE_SOURCES';

export const ADD_SOURCE = 'ADD_SOURCE';
export const UPDATE_SOURCE = 'UPDATE_SOURCE';
export const DELETE_SOURCE = 'DELETE_SOURCE';

export const SOURCE_TYPE_AWS_BUCKET = 'AWS_BUCKET';
export const SOURCE_TYPE_DEFAULT = SOURCE_TYPE_AWS_BUCKET;
export const SOURCE_TYPES = [SOURCE_TYPE_AWS_BUCKET];
