export const FETCH_TRACKS = 'FETCH_TRACKS';
export const FETCH_TRACKS_DONE = 'FETCH_TRACKS_DONE';
export const FILTER_TRACKS = 'FILTER_TRACKS';
export const REPLACE_TRACKS = 'REPLACE_TRACKS';
export const SET_ACTIVE_COLLECTION = 'SET_ACTIVE_COLLECTION';
export const SET_TARGET_COLLECTION = 'SET_TARGET_COLLECTION';
